# Ansible playbook to provision OpenVPN on a remote host.

- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  pre_tasks:
    - name: Wait up to 300 seconds (5m) for EC2 bootstrap
      wait_for_connection:
        timeout: 300
    - name: Gather facts
      setup:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
  roles:
    - kyl191.openvpn
  vars:
    openvpn_proto: tcp
    openvpn_dualstack: false
    # network (without cidr) - ensure this DOES NOT clash with any subnets in AWS
    openvpn_server_network: "10.99.0.0"
    # ip addr/dns name that gets added into client configs
    openvpn_server_hostname: vpn.balded-gibbon.com
    # disable this as it only works with Windows
    openvpn_client_register_dns: false
    manage_firewall_rules: false
    # this allows multiple clients to connect using the same key
    openvpn_duplicate_cn: true
    clients:
      - vpnclient

  tasks:
    - name: Grab a list of VPN configuration files
      find: paths="/etc/openvpn/" recurse=no patterns="*.ovpn"
      register: ovpn_config

    - name: Download VPN configuration tarball from the server
      fetch:
        src: "{{ item.path }}"
        dest: ./
        flat: yes
      with_items: "{{ ovpn_config.files }}"

    - name: Install aws-cli
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - awscli